---
title: "Do's and Don'ts For Discussing Data Inside the ADRF"
---

It is important to protect the confidential data that is inside the ADRF in communicating with your team-mates. The general rule is that you should never take any exact number out of the ADRF. This means you should never write down or share any number by text, screenshot, or share an image even with a team-mate. The rules have become more complicated now that everything is online, because even though your team-mates are "safe people", and zoom conversations are password protected and encrypted, we'd rather err on the side of caution when sharing information over zoom.

This cheat sheet summarizes some of the rules that apply to discussing data **before it has been exported from the ADRF and passed the ADRF team's disclosure review.** If you are unsure about a specific situation, please ask a Coleridge at [support\@coleridgeinitiative.org](mailto:support@coleridgeinitiative.org "mailto:support@coleridgeinitiative.org").

## **Exact Numbers**

Do not describe a statistic in exact numbers. If you would like to communicate these values while not in person, you can have a private discussion via the projects drive inside the ADRF.

*Example*: If an average within a specific group was 5,000, you would need to convey this average on the projects drive.

## **Comparing Values**

When comparing values, you are permitted to say that one value is more than, less than, or about the same as another. However, you cannot refer to the exact difference between the two numbers.

In practice, you can use pluses and minuses to convey differences between values for data that has not been exported from the ADRF.

*Example*: "The mean for Group A was roughly the same as the mean for Group B, but these values were both greater than that of Group C."

## **Percentages/Proportions**

Percentages and proportions also cannot be directly mentioned. Instead, you can refer to the percentage/proportion within 25%.

*Example*: If a proportion was 30%, you could say "The proportion is about 25%" or "The proportion is between 25% and 50%."
