---
title: "ADRF - FAQs"
---

## FAQs

::: {.callout collapse="true"}
## **How do I set up my Multifactor Authentication**

You should be prompted to set up multifactor authentication when you create your account, the options are SMS, voice call, email and the Okta verify application.
:::

::: {.callout collapse="true"}
## **Can I set up more than one form of Multifactor Authentication?**

This is recommended. If you lose access to one form of MFA, you would still be able to gain access to your account using an alternative. To do so, please log on to https://adrf.okta.com and select your name on the top right and click settings. Here you can modify or set up your SMS, voice call, email or Okta multifactor authentication.
:::

::: {.callout collapse="true"}
## **How can I reset my password?**

You can use the "Need help signing in?" option on the sign on page (https://adrf.okta.com) which will send a link to your email to reset your password. You may have to verify your identify by answering security questions which you set up when creating your account.
:::

::: {.callout collapse="true"}
## **What if I do not remember my security questions or if I get locked out?**

You would have to reach out to support at support\@coleridgeinitiative.org to have your account unlocked and you would have to reset your security questions so that you can recover your account in the future.
:::

::: {.callout collapse="true"}
## **I can log into the ADRF but my desktop and DS application just show blank pages.**

Please ensure the connection to ADRF is not being blocked by your organizations VPN and/or firewall (try using a device not connected to your organization's network) and reach out to support\@coleridgeinitiative.org.
:::

::: {.callout collapse="true"}
## **I saved a file in the C: drive or in the Desktop. When I logged back in, the file is no longer there. Can you restore it?**

The ADRF is a temporary workspace environment, files left on the desktop will be removed when you log out of your session, and we cannot restore these files. [See section -@sec-tempworkspace] Best practice is to store files in your user folder on the U: drive
:::


::: {.callout collapse="true"}
## **How do I open an ipynb notebook?**

On the desktop you should find an icon for JupyterLab, when you click that, a command prompt and a browser window are opened up, leave the command prompt running. You should be able to open the file by selecting File -\> Open From Path  and providing the path to the folder containing the ipynb notebook.
:::

::: {.callout collapse="true"}
## **How can I ingest publicly available data into the ADRF?**

Please open a support request by sending an email to support\@coleridgeinitiative.org.  Include the dataset you wish to have available inside the ADRF and documentation that confirms that the dataset is public.
:::

::: {.callout collapse="true"}
## **Where can I access publicly available data from within the ADRF?**

Publicly available data is stored in the schema ds_public_1.
:::

::: {.callout collapse="true"}
## **Where is my project or training related data stored?**

All project and training related databases are prefixed with 'pr\_' (for project) or 'tr\_' (for training). You may use this space when creating intermediate datasets or as a "working space". All project members have read and write access to this area (specific to your project).
:::

::: {.callout collapse="true"}
## **My data is not in a relational format. Where can I find these files?**

Read-only non-relational data are stored in the G:\\ drive on Windows Explorer. Project specific non-relational data and files are stored in project specific folders that are prefixed with 'pr\_' or 'tr\_'.  The location of these folders are in the P:\\ drive on Windows Explorer.
:::

::: {.callout collapse="true"}
## **What is the difference between the P:, U: and G: drives?**

Each drive location has a different purpose and access rule:\
          P:  Project specific files shared by ALL project members\
          U:  User personal space.  Only the user has read/write access to this area.\
          G:  Non-relational datasets.  Read-only access to authorized users only.
:::

::: {.callout collapse="true"}
## **I need to process a large amount of relational data. What is the destination location?**

The best practice is to process the data where it is currently located.  If the data is in a relational database, perform as much of your processing using Redshift to make the most efficient use of resources (i.e. filtering, sorting, etc). 
:::
