---
title: "Storing Analytic Results"
---

## **Eligible Locations**

### User Drive

The U: drive is your user drive; it's where you will store any files you are working on. Only the user will have access to the U: drive. For example, if user A wants to share information with user B who is on the same project, user A will need to save files to a P: drive folder and not folders in their U: drive since user B will not be able to access user A's U: drive.

### Project Drive

The P: drive also allows permanent storage. This drive is accessible by anyone on the same project, but not across projects. This is the only drive outside of the user drive where saved files will not be erased after logging out of the ADRF.

### SQL

Each project will have a project-specific database created. All members of the project will have read and write permissions for data and may also create their own objects (tables, etc.). The project databases are prefixed with pr-.

## **Ineligible Locations**

The G: drive (data), the L: drive (Libs), and the desktop are not eligible for long-term file storing. You won't have permissions to write to either the G: drive or the L: drive. The desktop will function only as temporary storage---as soon as a user is logged out of the ADRF, your desktop will be cleared. Additionally, since Wi-Fi connectivity can be imperfect, desktop storage for any amount of time is not recommended.

## **Storage Size Restrictions**

Storage size varies by project, but is capped at a predetermined amount. Additional storage costs may vary depending on the resource requirements. <https://aws.amazon.com/appstream2/pricing/>

## **Best Practices**

To save storage space, try not to save raw data tables---in particular, don't save copies of or large subsets of data that are already available through standard sources. Instead, access data through the methods described in the prior sections here, as appropriate for your programming language or program.

Organize folders in a way that makes sense for your particular project. For example, you might have folders for a particular analysis or sub-projects. Dates on file names can be helpful for version control.

Keep tabs on how much storage you are using compared to the allocated amount of storage.
