---
title: "Obtaining ADRF Access and Account Set Up"
---

## **Requesting an Account**

-   [Agency-affiliated researcher.]{.underline} If you are an agency-affiliated researcher, your agency will set up an ADRF account for you.

-   [Individual part of a training program]{.underline}. If you are part of a training program, Coleridge Initiative will create an account for you once you have been accepted into the program.

## **Account Registration and Onboarding Tasks**

-   You will receive an email invitation to activate your account. The email will come from [http://okta.com](http://okta.com/ "http://okta.com"), so please make sure that it doesn't get caught in your email spam filter. Follow the steps outlined in the email to set up your password and your multi-factor authentication preferences. Clink on the link below to watch a video walking through the steps.

-   After activating your account, you will be logged in to the ADRF Applications page. Proceed to the Management Portal by clicking on the icon.

-   In the Management Portal, you will notice a "Onboarding Tasks" section within "Admin Tasks" with a number of items you will need to complete before you can gain access to the project space. Refer to the next section for details about the onboarding process.

## **Obtaining ADRF Access**

-   Agency-affiliated researcher. If you are an agency-affiliated researcher using an agency-sponsored account, you will be granted ADRF access once you complete your onboarding tasks and required data access agreements. If you are a self-paying agency-affiliated researcher, your ADRF access is conditional on receipt of payment. If your institution of Office of Sponsored Programs will be submitting payment on your behalf, please be aware of potential access delays. Whenever possible, the Coleridge Initiative advises paying with a personal credit card or institutional payment card and using the generated invoice to request reimbursement.

-   Individual part of a training program. If you are part of a training program, you will be granted ADRF access once you complete your onboarding tasks and required data access agreements.

## **More Information**

If you have any questions, please contact [support\@coleridgeinitiative.org](mailto:support@coleridgeinitiative.org "mailto:support@coleridgeinitiative.org").
